### PR TITLE
Adding code to Navbar.js file to create the navbar

### PR DESCRIPTION
**Pull request by willtemmy**
Created component navbar which has a link to Home, Products, and the Cart, it also has a Searchbar

### CODE REVIEW

**Review by MarsMwau — APPROVED** [review]
Good Job!

**Review by 0714424507 — APPROVED** [review]
nice

**Review by JoyMalinda — APPROVED** [review]
approved

**Review by Max-Mahinda — COMMENTED** [review]
yes

**Review by Max-Mahinda — APPROVED** [review]

**Review by Max-Mahinda — COMMENTED** [review]
yes

**Review by Max-Mahinda — COMMENTED** [review]
yes

**Review by Max-Mahinda — APPROVED** [review]
yes

**Comment by MarsMwau** [comment]
Added The NavBar

**Pull request merged**
